export const themes = {
    // Dark Themes (Prioritized)
    midnight: {
        name: "Midnight Calm",
        primary: "bg-indigo-600 hover:bg-indigo-700",
        primaryText: "text-white",
        secondary: "bg-slate-700 hover:bg-slate-600",
        secondaryText: "text-slate-200",
        background: "bg-gradient-to-br from-slate-900 via-slate-800 to-indigo-900",
        cardBackground: "bg-slate-800/90 backdrop-blur-sm",
        border: "border-slate-700",
        text: "text-slate-100",
        textMuted: "text-slate-400",
        input: "bg-slate-700/80 border-slate-600 focus:border-indigo-500 focus:ring-indigo-500",
        inputText: "text-slate-100",
    },

    forest: {
        name: "Forest Night",
        primary: "bg-emerald-600 hover:bg-emerald-700",
        primaryText: "text-white",
        secondary: "bg-slate-700 hover:bg-slate-600",
        secondaryText: "text-emerald-100",
        background: "bg-gradient-to-br from-slate-900 via-emerald-900 to-slate-800",
        cardBackground: "bg-slate-800/90 backdrop-blur-sm",
        border: "border-slate-700",
        text: "text-slate-100",
        textMuted: "text-emerald-300",
        input: "bg-slate-700/80 border-slate-600 focus:border-emerald-500 focus:ring-emerald-500",
        inputText: "text-slate-100",
    },

    ocean: {
        name: "Deep Ocean",
        primary: "bg-blue-600 hover:bg-blue-700",
        primaryText: "text-white",
        secondary: "bg-slate-700 hover:bg-slate-600",
        secondaryText: "text-blue-100",
        background: "bg-gradient-to-br from-slate-900 via-blue-900 to-slate-800",
        cardBackground: "bg-slate-800/90 backdrop-blur-sm",
        border: "border-slate-700",
        text: "text-blue-50",
        textMuted: "text-blue-300",
        input: "bg-slate-700/80 border-slate-600 focus:border-blue-500 focus:ring-blue-500",
        inputText: "text-slate-100",
    },

    lavender: {
        name: "Lavender Dreams",
        primary: "bg-purple-600 hover:bg-purple-700",
        primaryText: "text-white",
        secondary: "bg-slate-700 hover:bg-slate-600",
        secondaryText: "text-purple-100",
        background: "bg-gradient-to-br from-slate-900 via-purple-900 to-slate-800",
        cardBackground: "bg-slate-800/90 backdrop-blur-sm",
        border: "border-slate-700",
        text: "text-purple-50",
        textMuted: "text-purple-300",
        input: "bg-slate-700/80 border-slate-600 focus:border-purple-500 focus:ring-purple-500",
        inputText: "text-slate-100",
    },

    charcoal: {
        name: "Charcoal Zen",
        primary: "bg-gray-600 hover:bg-gray-700",
        primaryText: "text-white",
        secondary: "bg-gray-700 hover:bg-gray-600",
        secondaryText: "text-gray-200",
        background: "bg-gradient-to-br from-gray-900 via-gray-800 to-slate-900",
        cardBackground: "bg-gray-800/90 backdrop-blur-sm",
        border: "border-gray-700",
        text: "text-gray-100",
        textMuted: "text-gray-400",
        input: "bg-gray-700/80 border-gray-600 focus:border-gray-500 focus:ring-gray-500",
        inputText: "text-gray-100",
    },
    forestTwilight: {
        name: "Forest Twilight",
        primary: "bg-emerald-600 hover:bg-emerald-700",
        primaryText: "text-white",
        secondary: "bg-stone-600 hover:bg-stone-500",
        secondaryText: "text-stone-100",
        background: "bg-gradient-to-br from-stone-900 via-green-900 to-emerald-900",
        cardBackground: "bg-stone-800/85 backdrop-blur-sm",
        border: "border-stone-700",
        text: "text-stone-100",
        textMuted: "text-stone-400",
        input: "bg-stone-800/90 border-stone-600 focus:border-emerald-400 focus:ring-emerald-400",
        inputText: "text-stone-100",
        accent: "bg-lime-500 hover:bg-lime-600",
        accentText: "text-white"
    },
    warmEmber: {
        name: "Warm Ember",
        primary: "bg-rose-600 hover:bg-rose-700",
        primaryText: "text-white",
        secondary: "bg-stone-600 hover:bg-stone-500",
        secondaryText: "text-stone-100",
        background: "bg-gradient-to-br from-stone-900 via-red-900 to-rose-900",
        cardBackground: "bg-stone-800/85 backdrop-blur-sm",
        border: "border-stone-700",
        text: "text-stone-100",
        textMuted: "text-stone-400",
        input: "bg-stone-800/90 border-stone-600 focus:border-rose-400 focus:ring-rose-400",
        inputText: "text-stone-100",
        accent: "bg-orange-500 hover:bg-orange-600",
        accentText: "text-white"
    },

    // Light Themes (Softer tones)
    serenity: {
        name: "Serenity",
        primary: "bg-slate-500 hover:bg-slate-600",
        primaryText: "text-white",
        secondary: "bg-slate-50 hover:bg-slate-100",
        secondaryText: "text-slate-700",
        background: "bg-gradient-to-br from-slate-50 to-blue-50",
        cardBackground: "bg-white/90 backdrop-blur-sm",
        border: "border-slate-200",
        text: "text-slate-800",
        textMuted: "text-slate-500",
        input: "bg-white/80 border-slate-200 focus:border-slate-400 focus:ring-slate-400",
        inputText: "text-slate-800",
    },

    sage: {
        name: "Sage Garden",
        primary: "bg-green-500 hover:bg-green-600",
        primaryText: "text-white",
        secondary: "bg-green-50 hover:bg-green-100",
        secondaryText: "text-green-700",
        background: "bg-gradient-to-br from-green-50 to-emerald-50",
        cardBackground: "bg-white/90 backdrop-blur-sm",
        border: "border-green-200",
        text: "text-green-800",
        textMuted: "text-green-600",
        input: "bg-white/80 border-green-200 focus:border-green-400 focus:ring-green-400",
        inputText: "text-green-800",
    },

    mist: {
        name: "Morning Mist",
        primary: "bg-blue-400 hover:bg-blue-500",
        primaryText: "text-white",
        secondary: "bg-blue-50 hover:bg-blue-100",
        secondaryText: "text-blue-700",
        background: "bg-gradient-to-br from-blue-50 to-cyan-50",
        cardBackground: "bg-white/90 backdrop-blur-sm",
        border: "border-blue-200",
        text: "text-blue-800",
        textMuted: "text-blue-500",
        input: "bg-white/80 border-blue-200 focus:border-blue-400 focus:ring-blue-400",
        inputText: "text-blue-800",
    },

    warm: {
        name: "Warm Embrace",
        primary: "bg-amber-500 hover:bg-amber-600",
        primaryText: "text-white",
        secondary: "bg-amber-50 hover:bg-amber-100",
        secondaryText: "text-amber-700",
        background: "bg-gradient-to-br from-amber-50 to-orange-50",
        cardBackground: "bg-white/90 backdrop-blur-sm",
        border: "border-amber-200",
        text: "text-amber-800",
        textMuted: "text-amber-600",
        input: "bg-white/80 border-amber-200 focus:border-amber-400 focus:ring-amber-400",
        inputText: "text-amber-800",
    },
    peach: {
        name: "Peach Blossom",
        primary: "bg-orange-300 hover:bg-orange-400",
        primaryText: "text-white",
        secondary: "bg-orange-50 hover:bg-orange-100",
        secondaryText: "text-orange-700",
        background: "bg-gradient-to-br from-orange-50 to-amber-50",
        cardBackground: "bg-white/85 backdrop-blur-sm",
        border: "border-orange-100",
        text: "text-orange-800",
        textMuted: "text-orange-500",
        input: "bg-white/80 border-orange-200 focus:border-orange-300 focus:ring-orange-300",
        inputText: "text-orange-800",
    },
    mint: {
        name: "Mint Breeze",
        primary: "bg-teal-400 hover:bg-teal-500",
        primaryText: "text-white",
        secondary: "bg-teal-50 hover:bg-teal-100",
        secondaryText: "text-teal-700",
        background: "bg-gradient-to-br from-teal-50 to-cyan-50",
        cardBackground: "bg-white/80 backdrop-blur-sm",
        border: "border-teal-100",
        text: "text-teal-800",
        textMuted: "text-teal-500",
        input: "bg-white/75 border-teal-200 focus:border-teal-300 focus:ring-teal-300",
        inputText: "text-teal-800",
    },
    bumblebee: {
        name: "Bumblebee",
        primary: "bg-yellow-300 hover:bg-yellow-400",
        primaryText: "text-yellow-800",
        secondary: "bg-orange-300 hover:bg-orange-400",
        secondaryText: "text-orange-800",
        background: "bg-gradient-to-br from-white via-gray-50 to-yellow-50",
        cardBackground: "bg-white/95 backdrop-blur-sm",
        border: "border-gray-200",
        text: "text-gray-800",
        textMuted: "text-gray-600",
        input: "bg-white border-gray-300 focus:border-yellow-400 focus:ring-yellow-400",
        inputText: "text-gray-800",
    },
    retro: {
        name: "Retro",
        primary: "bg-red-400 hover:bg-red-500",
        primaryText: "text-red-900",
        secondary: "bg-teal-200 hover:bg-teal-300",
        secondaryText: "text-teal-800",
        background: "bg-gradient-to-br from-orange-50 via-yellow-50 to-red-50",
        cardBackground: "bg-orange-50/95 backdrop-blur-sm",
        border: "border-orange-200",
        text: "text-orange-900",
        textMuted: "text-orange-700",
        input: "bg-orange-50 border-orange-200 focus:border-red-400 focus:ring-red-400",
        inputText: "text-orange-900",
    },
};
